Урок 4
dronline872/learningGo1 pull request #4
Opened 2021-09-30 08:37 UTC by dronline872

2021-10-02 07:25 UTC, goarchitecture requested changes
Хороший старт. Исправьте по комментариям

2021-10-02 07:25 UTC, goarchitecture commented on lesson_4/app.go
> +	for i := 1; i < len(listNumbers); i++ {
сортировка должна быть в отдельной функции

2021-10-02 07:25 UTC, goarchitecture commented on lesson_4/app.go
> +	fmt.Println("Введите целые числа через запятую:")
давайте не будем ругать юзера за пробелы. Там где "через запятую", обычно разрешает и с пробелами и без них

2021-10-04 20:58 UTC, dronline872 commented on lesson_4/app.go
> +	fmt.Println("Введите целые числа через запятую:")
Исправил

2021-10-04 20:59 UTC, dronline872 commented on lesson_4/app.go
> +	for i := 1; i < len(listNumbers); i++ {
@goarchitecture  вынес в отдельную функцию

2021-10-29 19:07 UTC, goarchitecture reviewed
отлично

2021-10-31 12:02 UTC, merged